name: DSMShop
main: com.syrical.dsmshop.DSMShop
version: 2.0 Alpha
commands:
    shop:
      description: Opens Shop GUI
      usage: /<command>
    checkprice:
      description: Checks price of an item
      usage: /<command> <world> <item>
    sell:
      description: Open Sell Menu
      usage: /<command>
    balance:
      aliases: [bal]
      description: Gives current balance
      usage: /<command>
    addcredits:
      description: Add credits to plyaer's balance
      usage: /<command>
    removecredits:
      description: Removes credits from plyaer's balance
      usage: /<command>
    pay:
      description: Pay another player
      usage: /<command>
    shopcreate:
      description: Create a shop sign
      usage: /<command>